name: Wallets Detector

on:
  schedule:
    - cron: "0 4 * 1 *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest --xvfb